language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libglib2.0-dev
before_install:
  - export PYGTK_VERSION=2.24.0
  - export PYGTK_PATH=$HOME/pygtk/
  - export PYGTK_INST=$HOME/pygtk-inst/
  - mkdir $PYGTK_PATH
  - cd $PYGTK_PATH
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-"$PYGTK_VERSION".tar.bz2 -O pygtk.tar.bz2
  - tar -xf pygtk.tar.bz2
  - cd pygtk-"$PYGTK_VERSION"
  - ./configure --prefix=$PYGTK_INST
  - make
  - sudo make install
install:
  - python setup.py install
script: "python setup.py test"
