language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-gtk2 python-gtk2-dev libgtk2.0-dev libglib2.0-dev
install:
  - python setup.py install
script: "python setup.py test"
