language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libglib2.0-dev
      - libgirepository1.0-dev
      - python-cairo
      - python-cairo-dev
      - python-gobject
      - python-gobject-dev
before_install:
  - export WORKDIR=$HOME/build/
  - export PYGTK_VERSION=2.24.0
  - export PYGTK_PATH=$WORKDIR/pygtk/$PYGTK_VERSION
  - mkdir -p $PYGTK_PATH
  - cd $PYGTK_PATH
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-"$PYGTK_VERSION".tar.bz2 -O pygtk.tar.bz2
  - tar -xf pygtk.tar.bz2
  - cd pygtk-"$PYGTK_VERSION"/
  - ./configure
  - make
  - sudo make install
install:
  - python setup.py install
script: "python setup.py test"
